apiVersion: download.beebs.dev/v1
kind: Download
metadata:
  labels:
    app.kubernetes.io/name: download
    app.kubernetes.io/instance: download-sample
  name: test-download-live
spec:
  inputURL: "https://www.youtube.com/watch?v=Wb3UrJjAac4"
  output:
    s3:
      bucket: "my-operator-downloads"
      key: "dog-eats-burrito-in-one-second.mp4"
      secretRef: "s3-creds"